version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: nextjs_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped
    networks:
      - nextjs_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    container_name: nextjs_app
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
    networks:
      - nextjs_network
    restart: unless-stopped

networks:
  nextjs_network:
    driver: bridge

volumes:
  postgres_data:
